// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
export const environment = {
  production: true,
  fetchIntegrate: 'true',
  appKey:
    'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibXVoYW1tYWQucml4dmFuLndhaGVlZEBnbWFpbC5jb20iLCJleHAiOjE2NzYyMzA4MjYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjQ0MzY5LyIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjQyMDAifQ.NlSFdJSUQfDF0_hbXkfL_smZkfV8b9KFt4ToBFZDzO0',
  googleclientId:
    '867983649889-mu8n73d0clq5qvan437dmop87a9ofhot.apps.googleusercontent.com',
  googleclientSecret: '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',
  facebookclientId: '439165040679685',
  facebookclientSecret: 'b1ece7f6d042edefbb22c87815804c5b',
  instagramclientId: '243324534762428',
  instagramclientSecret: 'b48f01922a081352c29ed641abbc4f1b',
  linkdinclientId: '86gfpczqqo16t6',
  linkdinclientSecret: '4wp2Zjzqjw3PYAdt',
  twitterclientId: '57617762-IWEThd14hGdgr3bXuVNmLdb60Lo9OLEVJ1cFUE4JF',
  twitterclientSecret: 'Ex1XpdfYMFEAtWBJn9XOrtfxyu19INzNaPV155vocLomG',
  store: { types: { local: 'LS' } },
  title: 'abc',
  clientNumber: '923112744502',
  FbBaseUrl: 'https://firstyellowmouse47.conveyor.cloud/api/',
  // FbBaseUrl: 'https://nextsparklypen70.conveyor.cloud/api/',
  YoutubeBaseUrl: 'https://tube.360scrm.com/api/',
  TwitterBaseUrl: 'https://tweet.360scrm.com/api/',
  EmailBaseUrl: 'https://mail.360scrm.com/api/',
  SmsBaseUrl: 'https://text.360scrm.com/api/',
  // WhatsappBaseUrl: 'https://whats.360scrm.com/api/',
  // WhatsappBaseUrl: 'https://waservice.enteract.live/api/',
  WebChatBaseUrl: 'https://chat.360scrm.com/api/',
  KelisteningBaseUrl: 'https://listen.enteract.live/backend/api/',
  KemediaBaseUrl: 'https://kemedia.360scrm.com/api/',
  KescrmBaseUrl: 'https://kescrm.360scrm.com/',

  IdentityBaseUrl: 'https://identity-engage.enteract.app/api/',
  CommonBaseUrl: '',
  SignalRCommonBaseUrl: '',
  ProfileBaseUrl: '',
  ServiceBaseUrl: '',
  ConsoleBaseUrl: '',
  LinkedInBaseUrl: '',
  BotBaseUrl: '',
  ReportsBaseUrl: '',
  KeReportsBaseUrl: '',

  
  botBaseUrl: 'https://bot-engage.enteract.app/api/',
  chatBotBaseUrl: 'https://entertainerbot.enteract.app',
  botsBaseUrl: 'http://3.1.47.150:5000/bots/',
  botConfigBaseUrl: 'https://linked.360scrm.com/api/',

  // // for rule
  faceRoxBaseUrl: 'https://smallreddart56.conveyor.cloud/api/',

  botMoniteringBaseUrl: 'https://flowbot.enteract.app/',
  flowBot: 'https://flowbot.enteract.app/',
  intentBot: 'https://intentbot.enteract.app/',
  autoresponderbaseurl: 'https://enfacebookbackend.enteract.live/api/',
  instagramBaseUrl: 'https://insta.360scrm.com/api/',
  linkdinBaseUrl: 'https://enlinkedinbackend.enteract.live/api/',
  youtubeBaseUrl: 'https://tube.360scrm.com/api/',
  whatsappBaseUrl: 'https://enwhatsappbackend.enteract.live/api/',
  gSuitBaseUrl: 'https://mail.360scrm.com/api/',
  playStoreBaseUrl: 'https://play.360scrm.com/api/',
  exchangeEmailBaseUrl: 'https://enexchangebackend.enteract.live/api/',
  metaWhatsapp: 'https://mbwhats.360scrm.com/api/',
  CCMSURL: 'https://haccms.ibex.co/jomo/api/',
  JomoAccessToken: '407ecdb2308d5cc24e9f5d24a779e4a3151357bb',
  links: {
    identity: {
      login: 'Authentication/Login',
      //Company:"Teams/FetchAll",
      accesses: 'Teams/Accesses',
      properties: 'Teams/Properties',
      accessteam: 'Teams/Previews',
      permissionteam: 'Teams/Previews',
      TeamsAccesses: 'Teams/Fetch',
      AllTeams: 'Teams/FetchAll', // new to review
      AddTeam: 'Accesses/Teams',
      TeamProperties: 'Accesses/Properties',
      // accessrole: 'Roles/NewPreviews', //"Permissions/role",
      RolesPermissions: 'Roles/NewPreviews', //"Permissions/role",
      ReportsMenus: 'Report/GetReportsPreview',
      ConsoleMenus: 'Roles/NewMenuPreviews',
      //RolesPermissions: 'Roles/Fetch',
      permissions: 'Roles/Permissions',
      RoleProperties: 'Permissions/Properties',
      AddRole: 'Permissions/Roles',
      //UserRoles: 'Roles/GetActors',
      UserRoles: 'Roles/GetActor',
      //UserTeams: 'Teams/TeamsByUser',
      UserTeams: 'Teams/GetAllTeams',
      AddUser: 'Identity/Add',
      UpdateUser: 'Identity/Update',
      DeleteUser: 'Identity/Delete',
      AllUsers: 'Users/GetAll',
      GetUserById: 'Users/GetById/',
      // For console skill setup
      channels: 'Console/Properties/Channel/Tree/0',
      consoleChannls: 'Channels/GetChannelsTree',
      routing: 'Console/Properties/routing/Tree/0',
      deleteRoles: 'Permissions/Delete',
      ////// Later Align in Console/////
      defaultTags: 'Tags/GetTags',
      getUserRoles: 'Roles/GetUserActor',
      getVoiceToken:'Authentication/GetVoiceToken'
    },
    console: {
      AddUser: 'Users/CreateUser',
      CreateMessageTemplate: 'Template/Add',
      getAllMessages: 'Template/GetAll',
      botConfigDetails: 'ProfilePagesBotConfig/GetAll',
      UpdateStatus: 'ProfilePagesBotConfig/UpdateStatus',
      ViewBotConfig: 'ProfilePagesBotConfig/GetById',
      addTemplate: 'Template/Add',
      updateTemplate: 'Template/Update',
      deleteMessages: 'Template/Delete',
      deleteBotConfig: 'ProfilePagesBotConfig/Delete',
      getQuickReply: 'QuickReply/GetAll',
      getActiveQuickReply: 'QuickReply/GetAllActiveQuickReplies',
      addQuickReply: 'QuickReply/Add',
      updateQuickReply: 'QuickReply/Update',
      deleteQuickReply: 'QuickReply/Delete',
      getSlaPolicy: 'SLAPolicies/GetAll',
      addSlaPolicy: 'SLAPolicies/Add',
      updateSlaPolicy: 'SLAPolicies/Update',
      getPolicyById: 'SLAPolicies/GetById',
      getBusinessHoursById: 'BusinessHours/GetById',
      deleteSlaPolicy: 'SLAPolicies/Delete',
      getOperationalHours: 'SLAPolicies/GetOperationalHours',
      getBusinessHours: 'BusinessHours/GetAll',
      addBusinessHours: 'BusinessHours/Add',
      deleteBusinessHours: 'BusinessHours/Delete',
      updateBusinessHours: 'BusinessHours/Update',
      getBusinessById: 'BusinessHours/GetById',
      getEntractRoute: 'EnteractRoute/GetAll',
      addEntractRoute: 'EnteractRoute/Add',
      updateEntractRoute: 'EnteractRoute/Update',
      deleteEntractRoute: 'EnteractRoute/Delete',
      getAllSkills: 'Skill/GetAll',
      addSkill: 'Skill/Add',
      addBotConfig: 'ProfilePagesBotConfig/Add',
      deleteSkill: 'Skill/Delete',
      getAllWing: 'Teams/GetAllWing',
      getPolicyByWing: 'SLAPolicies/GetByWing',
      getCompanyTeams: 'Teams/GetCompanyTeams',

      // service Base rules
      getEntitiesRules: 'EntityConfigs/GetEntities',
      getEntitiesProperties: 'EntityConfigs/GetEntitiesProperties',
      addRule: 'RuleConfigs/Add',
      getFbRule: 'RuleConfigs/GetAll',
      softDeleteFb: 'RuleConfigs/Delete',
      addEmailRule: 'RuleBuilder/Add',
      // getTagsAll: 'Tags/GetAll',
      getTagsByCompanyId: 'Tags/GetSupreamTags',
      updateSkill: 'Skill/Update',
      getSkillsbyId: 'Skill/GetById',
      getSkills: 'Skill/GetSkills',
      getAllProfile: 'Profile/GetAll',
      addProfile: 'Profile/Add',
      attachFacebookPage: 'ProfileManagement/RegisterProfile',
      getTags: 'Tags/GetTags',
      getTagById: 'Tags/GetById',
      addTags: 'Tags/Add',
      updateTag: 'Tags/Update',
      deleteTags: 'Tags/StatusUpdate',
      getTagsByComayId: 'Tags/GetTagsByCompayId',
      getAllRules: 'Rules/GetAll',
      getEntitiesRule: 'Rules/GetEntities',
      getRuleEntityProperties: 'Rules/GetEntitiesProperties/',
      getRuleById: 'Rules/GetById',
      addRules: 'Rules/Add',
      updateRules: 'Rules/Update',
      deleteRules: 'Rules/Delete',
      getTagsAll: 'Tags/GetAll',
      defaultTags: 'Tags/GetTags',
      quickReplyListForBazaar: 'QuickReply/GetAll',
      getAllTeams: 'Teams/GetAllTeams',
      addTeam: 'Teams/Add',
      updateTeam: 'Teams/Update',
      deleteTeam: 'Teams/Delete',
      teamGetById: 'Teams/FetchTeamById',
      getTeamType: 'Teams/GetTypes',
      deleteMultipleTeams: 'Teams/DeleteMultiple',
      getautoResponedFB: 'Configurations/GetCompanyTemplates',
      addFbResponed: 'Configurations/CreateTemplate',
      getCompanyPages: 'ProfileManagement/GetCompanyPages',
      getProfileDetails: 'ProfileManagement/GetProfileInfo?companyId=657',
      getServices: 'ServicesStructure/GetServices',
      getBotList: 'get_all',
      getActions: 'Configurations/GetAllAction',
      getPlatform: 'ServicesStructure/GetServices',
      getConsoleEntities: 'ServicesStructure/GetEntities',
      getConsoleEntityProperties: 'ServicesStructure/GetEntitiesProperties',
      getRuleType: 'Tags/GetServiceTags',
      getRuleTag: 'Tags/GetTagsBySupreamId',
      getServicetree: 'ServicesStructure/GetServiceTree',
      getTemplateStatus: 'Configurations/TemplateStatusToggler',
      deleteTemplate: 'Configurations/DeleteTemplate',
      getRuleStatus: 'RuleConfigs/UpdateRuleStatus',
      getTagsBySupreamId: 'Tags/GetTagsBySupreamId',
      addTagTeams: 'TagTeams/Add',
      updateTagTeams: 'TagTeams/Update',
      getSkillTeamById: 'TagTeams/GetById',
      deleteTagTeam: 'TagTeams/Delete',
      addAccessReports: 'ReportAcess/Add',
      getActors: 'Roles/GetActors',
      getReports: 'Report/GetReports',
      emailReport: 'EmailReport/GetEmailReport',
      wallboardReport: 'CommonReport/GetWallboard',
      perviousWallboardReport: 'CommonReport/GetPreviousWallboard',
      wallboardCSATReport: 'CommonReport/GetCurrentDayCSATReport',
      GetMonthToDateServiceLevel: 'CommonReport/GetMonthToDateServiceLevel',
      getPreviousInteractionDashboard: 'AgentReport/GetPreviousInteractionDashboard',
    },
    service: {
      addSurvey: 'Whatsapp/AddSurvey',
      addCSAT: 'Whatsapp/AddCSAT',
    },
    CCMS: {
      reason_types: 'Order/GetReasonTypes',
      reasons: 'Order/GetMainReasons/',
      GetTicketStatuses: 'Order/GetTicketStatuses',
      subReasons: 'Order/GetSubReasons/',
    },
    bot: {
      getAllChatBot: 'bots/get_all',
      addBot: 'bots/create',
      getbyid: 'bots/get',
      generateAugment: 'generative/augment',
      addIntend: 'intents/create',
      getIntents: 'intents/get',
      getReponse: 'responses/get',
      addResponse: 'responses/create',
      intentDelete: 'intents/delete',
      responseDelete: 'responses/delete',
      deleteChatBot: 'bots/deactivate',
      createRule: 'rules/create',
      createStory: 'stories/create',
      viewIntent: 'intents/get',
      viewResponse: 'responses/get',
      getRuleChatBot: 'rules/get',
      getStoriesChatBot: 'stories/get',
      ruleDelete: 'rules/delete',
      storyDelete: 'stories/delete',
      trainBot: 'models/train',
      createBotTrain: 'models/create',
      runChatBot: 'models/run',
      chatBotWdidget: 'chat',
      stopChatBot: 'models/stop',
    },
    common: {
      userlogin: 'SignalRConnector/UserLogin',
      RemoveTags: 'Tags/RemoveTagFromFeed',
      InsertSentiments: 'Tags/InsertSentimentForFeed',
      InsertTags: 'Tags/InsertTagsForFeed',
      ChannelList: 'Channel/GetChannelList',
      TagsList: 'Keyword/GetAllKeywordCategory',
      CommentRespond: 'Social/CommentRespond',
      MarkAsComplete: 'Social/MarkAsCompleted',
      SaveAsCompleted: 'Social/SaveAsCompleted',
      LikedByAdmin: 'Social/LikeByAdmin',
      QuickReplyList: 'Social/GetQuickReplyList',
      AssignQuerry: 'Query/AssignQuery',
      AgentsTeamList: 'Query/GetActiveAgent',
      AssignToAnotherAgent: 'Query/QueryAssignMultiUser',
      SlaList: 'WhatsAppReport/GetSLAChannelList',
      SlaDetail: 'WhatsAppReport/GetSLADetailList',
      SlaDM: 'WhatsAppReport/GetSLA_DM',
      ConversationDetail: 'Channel/GetChannelConversationDetail',
      MessageDetail: 'Channel/GetDMByPlatform',
      ReplyComment: 'Channel/ReplyChannelComment',
      HumanAgentTags: 'Tags/GetHumanAgentTag',
      AgentDetail: 'Team/GetById',
      UpdateBreak: 'SignalRConnector/UserOnBreak',
      InstaStats: 'Channel/GetInstagramPostStat',
      FbPostStats: 'Channel/GetFbPostStat',
      FbCommentStats: 'Channel/GetFbCommentStat',
      YoutubePostStats: 'Channel/GetYoutubePostStat',
      TwitterTweetStats: 'Channel/GetTwitterTweetStat',
      LinkedInPostStats: 'Channel/GetLinkedInPostStats',
      Menu: 'Menu/',
      profileDetails: 'Customer/GetCustomerById',
      updateProfile: 'Customer/UpdateCustomer',
      createTicket: 'Tickets/CreateTicket',
      allChannelsUnrespondedCounts: 'Channel/GetChannelUnrespondedCount',
      getOrderByCustomerEmailAddressOrPhoneNumber:
        'Order/GetOrdersByCustomerEmailAddress',
      dispositionHistory: 'Channel/GetDispositionHistory',
      markAllAsRead: 'Channel/ReadAllUnrespondedQuries',
      getAgentReport: 'WhatsAppReport/GetAgentTicketReport',
      getAllocatedProfiles: 'Query/GetAllocatedProfiles',
      repliesList: 'SentQueries/GetRepliesList',
      signOut: 'SignalRConnector/UserLogout',
      getCustomers: 'Customer/GetAllCustomersSocialProfile',
      updateStatus: 'Channel/UpdateMessageStatus',
      updateBotStatus: 'ProfilePagesBotConfig/UpdateStatus',
      insertTagOnProfile: 'Tags/InsertTagsProfileFeed',
      removeTagOnProfile: 'Tags/RemoveTagProfileFeed',
      hideUnhideMessage: 'Publisher/HideQuery',
      dispositionTags: 'Keyword/GetAllDisposition',
      removeAssignedQuery: 'Query/RemoveAssignQuery',
      sessionClose: 'Whatsapp/TerminateSupportSession',
      //Reports
      routeToAgents: 'WhatsAppReport/GetWhatsAppRouteToAgentReport',
      routeToAgentsCsv: 'WhatsAppReport/GetWhatsAppRouteAgentReportCSV',
      addUniqueCustomer: 'WhatsAppReport/GetWhatsAppUniqueCustomerReport',
      uniqueExportCsv: 'WhatsAppReport/GetWhatsAppUniqueCustomerReportCSV',
      addHandledBot: 'WhatsAppReport/GetWhatsAppBotHandleReport',
      addHandledBotCSV: 'WhatsAppReport/GetWhatsAppBotHandleReportCSV',
      addinboundoutbound: 'CommonReport/GetInboundOutboundReport',
      twitterReport: 'TwitterReport/GetTwitterReport',
      twitterSLAReport: 'WhatsAppReport/GetTwitterSLAReport',
      twitterProfileWiseReport: 'TwitterReport/GetTwitterProfileWiseReport',
      getUserList: 'Users/GetUserList',
      getSentimentData: 'Keyword/GetAllSentiments',
      addAgentPerformance: 'AgentReport/GetAgentPerformanceReport',
      shiftReport: 'CommonReport/GetShiftReport',
      getWhatsAppRawDataReport: 'WhatsAppReport/GetWhatsAppRawDataReport',
      downloadWhatsAppRawDataReport: 'WhatsAppReport/GetWhatsAppCSVData',
      postSocialRawData: 'CommonReport/GetAllChannelRawDataReport',
      downloadSocialRawData: 'CommonReport/GetAllChannelRawDataReportCSV',
      facebookReport: 'FacebookReport/GetFacebookReport',
      facebookProfile: 'FacebookReport/GetFacebookProfileWiseReport',
      getAllSocialMatrics: 'WhatsAppReport/GetAllSocialMediaMatricsReport',
      instagramReport: 'Instagramreport/GetInstagramReport',
      instagramProfile: 'Instagramreport/GetInstagramProfileWiseReport',
      getTagReport: 'CommonReport/GetTagsReport',
      downloadTagReport: 'CommonReport/GetAgentTagsReportCSV',
      getLinkedInReport: 'Activity/GetOrganizationSharedInsights',
      emailShiftReport: 'CommonReport/EmailShiftReport',
      getFollowUpCount: 'Channel/GetFollowUpCount',
      getLinkedInFollowers: 'Activity/GetOrganizationInsights',
      regionwiseReport: 'WhatsAppReport/GetRegionWiseReport',
      wordCloud: 'WhatsAppReport/GetKeWordCloud',
      areawiseReport: 'WhatsAppReport/GetAreaWiseReport',
      keMediaReport: 'MediaReport/GetMediaReport',
      PrintFeed: 'Media/GetMediaPrintList',
      CSATReport: 'Report/GetCSATReport',
      getInteractionReport: 'AgentReport/GetAgentPerformanceDashboard',
      // whatsapp bot interaction
      whatsappBotInteraction: 'Whatsapp/GetBotInteractionHistory',
    },
    facebook: {
      comments: 'Facebook/GetFbPost',
      messages: 'Facebook/GetFbDM',
      ProfileList: 'Facebook/GetFacebookProfileList',
      CommentReply: 'Facebook/CommentsReply',
      PageChatReply: 'Facebook/PageChatReplies',
      PostStats: 'Channel/GetFbPostStat',
      CommentStats: 'Channel/GetFbCommentStat',
    },
    instagram: {
      comments: 'Instagram/GetInstagramData',
      list: 'Instagram/GetChannelList',
      commentReply: 'Instagram/CommentReplayThread',
      postStats: 'Instagram/GetPostStat',
    },
    whatsapp: {
      messages: 'Whatsapp/GetWhatsappData',
      list: 'Whatsapp/GetWhatsappChannelList',
    },
    sms: {
      messages: 'SMS/GetSMSData',
      list: 'SMS/GetSMSChannelList',
      messageReply: 'SMS/SendSMSReply',
    },
    email: {
      emails: 'Email/GetMails',
      list: 'Email/GetLatestUnrespondedMails',
      emailReply: 'Email/SendEmailReply',
    },
    youtube: {
      comments: 'Youtube/GetPostsComments',
      list: 'Youtube/GetYoutubeAllUnresponded',
      commentReply: 'Youtube/CommentsReply',
      postStats: 'Youtube/GetPostsStats',
    },
    webChat: {
      messages: 'WebChat/GetUserChat',
      list: 'WebChat/GetUserList',
      messageReply: 'WebChat/SaveAgentReply',
    },
    profile: {
      KECSAT: 'CustomerCSAT/AddCSAT',
      getProfileInformationByID: 'ProfileInformation/GetProfileInformationByID',
      addProfileInformation: 'ProfileInformation/AddProfileInformation',
      searchProfileInformation: 'ProfileInformation/GetCustomerInformationByID',
      deattachProfileInformation: 'ProfileInformation/DeAttachProfile',
    },
    scrmReports: {
      facebookscrmReport: 'Facebook/FacebookGetPageReportStats',
      getfortesting: '/feedback/GetAllCampaignsWithCSAT',
    },
  },
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
